ALTER TABLE shops
ADD COLUMN IF NOT EXISTS free_delivery_radius_km NUMERIC(8, 2) DEFAULT 0;

ALTER TABLE shops
ADD COLUMN IF NOT EXISTS delivery_fee NUMERIC(10, 2) DEFAULT 0;

ALTER TABLE orders
ADD COLUMN IF NOT EXISTS delivery_fee NUMERIC(10, 2) DEFAULT 0;

ALTER TABLE orders
ADD COLUMN IF NOT EXISTS delivery_distance_km NUMERIC(8, 2);
